# Generated by Django 2.2.4 on 2019-10-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
