# Generated by Django 2.2.4 on 2019-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_', '0002_auto_20191021_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
