# Generated by Django 2.2.4 on 2019-10-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('class_', '0004_auto_20191021_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassJoined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'db_table': 'class_join',
                'unique_together': {('student', 'class_join')},
            },
        ),
    ]
