# Generated by Django 2.2.4 on 2019-10-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_', '0005_classjoined'),
    ]

    operations = [
        migrations.AddField(
            model_name='classjoined',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
