# Generated by Django 2.2.4 on 2019-11-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_', '0007_classjoined_is_suspend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classjoined',
            name='is_suspend',
        ),
    ]
