# Generated by Django 3.0.2 on 2020-01-30 12:31

import Account.validators
import Student.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[Student.validators.validate_name], verbose_name='Full Name')),
                ('username', models.CharField(help_text='Username can have "Numbers A-Z a-z _ - ." only', max_length=255, unique=True, validators=[Account.validators.validate_username])),
                ('designation', models.CharField(max_length=50, validators=[Student.validators.validate_designation])),
                ('profile_iamge', models.ImageField(blank=True, null=True, upload_to='media/Student')),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
