# Generated by Django 2.2.4 on 2019-10-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_', '0006_classjoined_is_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='classjoined',
            name='is_suspend',
            field=models.BooleanField(default=False),
        ),
    ]
