# Generated by Django 3.0.2 on 2020-01-27 16:25

import Manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=100, validators=[Manager.validators.validate_name], verbose_name='Full Name'),
        ),
    ]
