# Generated by Django 3.0.2 on 2020-01-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Manager')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Teacher')),
                ('is_student', models.BooleanField(default=False, verbose_name='Student')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Suspended')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Active')),
            ],
            options={
                'db_table': 'Account',
            },
        ),
    ]
